# Form implementation generated from reading ui file 'adminwin.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminWin(object):
    def setupUi(self, AdminWin):
        AdminWin.setObjectName("AdminWin")
        AdminWin.resize(723, 512)
        self.label = QtWidgets.QLabel(parent=AdminWin)
        self.label.setGeometry(QtCore.QRect(250, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(parent=AdminWin)
        self.pushButton.setGeometry(QtCore.QRect(510, 430, 171, 28))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(parent=AdminWin)
        self.listWidget.setGeometry(QtCore.QRect(50, 90, 631, 291))
        self.listWidget.setObjectName("listWidget")
        self.pushButton_2 = QtWidgets.QPushButton(parent=AdminWin)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 430, 171, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(AdminWin)
        QtCore.QMetaObject.connectSlotsByName(AdminWin)

    def retranslateUi(self, AdminWin):
        _translate = QtCore.QCoreApplication.translate
        AdminWin.setWindowTitle(_translate("AdminWin", "AdminWin"))
        self.label.setText(_translate("AdminWin", "Администратор"))
        self.pushButton.setText(_translate("AdminWin", "Добавить пользователя"))
        self.pushButton_2.setText(_translate("AdminWin", "Редактировать документ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWin = QtWidgets.QWidget()
    ui = Ui_AdminWin()
    ui.setupUi(AdminWin)
    AdminWin.show()
    sys.exit(app.exec())
