# Form implementation generated from reading ui file 'autorisation.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Autorisation(object):
    def setupUi(self, Autorisation):
        Autorisation.setObjectName("Autorisation")
        Autorisation.resize(521, 259)
        self.label = QtWidgets.QLabel(parent=Autorisation)
        self.label.setGeometry(QtCore.QRect(180, 30, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=Autorisation)
        self.lineEdit.setGeometry(QtCore.QRect(110, 100, 311, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Autorisation)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 150, 311, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(parent=Autorisation)
        self.pushButton.setGeometry(QtCore.QRect(220, 210, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Autorisation)
        QtCore.QMetaObject.connectSlotsByName(Autorisation)

    def retranslateUi(self, Autorisation):
        _translate = QtCore.QCoreApplication.translate
        Autorisation.setWindowTitle(_translate("Autorisation", "Form"))
        self.label.setText(_translate("Autorisation", "Авторизация"))
        self.lineEdit.setPlaceholderText(_translate("Autorisation", "логин"))
        self.lineEdit_2.setPlaceholderText(_translate("Autorisation", "пароль"))
        self.pushButton.setText(_translate("Autorisation", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Autorisation = QtWidgets.QWidget()
    ui = Ui_Autorisation()
    ui.setupUi(Autorisation)
    Autorisation.show()
    sys.exit(app.exec())
